version: "3"

networks:
    net:
        driver: bridge

services:
    laravel:
        privileged: true
        ports:
            - "9000:9000"
        expose:
            - "9000"
        build: ./laravel
        volumes:
            - .:/opt
            - ./docker/etc/php/php8/php.ini:/etc/php8/php.ini
            - ./docker/etc/php/php8/php8-fpm.d/www.conf:/etc/php8/php8-fpm.d/www.conf
        networks:
            - net

    scheduler:
        build: ./scheduler/
        user: "1000:1000"
        volumes:
            - .:/opt
        networks:
            - net
        links:
            - redis

    queue:
        build: ./queue/
        user: "1000:1000"
        mem_limit: 12G
        mem_reservation: 1G
        volumes:
            - .:/opt
        networks:
            - net
        links:
            - scheduler

    nginx:
        image: nginx
        volumes:
            - .:/opt/
            #      - ../../news-crawler-laravel-contents/docker/etc/nginx/:/etc/nginx/
            - ./docker/etc/nginx/FastcgiParams:/etc/nginx/FastcgiParams
            - ./docker/etc/nginx/ProxyPassparams:/etc/nginx/ProxyPassparams
            - ./docker/etc/nginx/contents.com.pem:/etc/nginx/contents.com.pem
            - ./docker/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"
        expose:
            - "80"
            - "443"
        networks:
            - net
        links:
            - laravel

    # frontend:
    #     image: node:12.22-alpine
    #     entrypoint: ""
    #     command: "sh -c 'cd /app; npm install; npm run build && npm run start'"
    #     volumes:
    #         - .client/:/app
    #     environment:
    #         HOST: 0.0.0.0
    #     ports:
    #         - "3000:3000"
    #     expose:
    #         - "3000"
    #     networks:
    #         - net
    #     links:
    #         - laravel

    redis:
        image: redis:4-alpine
        ports:
            - 6379:6379
        volumes:
            - ./data/redis:/data
        networks:
            - net
